### PR TITLE
Challenge 7 svg nft init

### PR DESCRIPTION
**Pull request by rin-st**
SVG NFT Challenge based on [Loogies](https://github.com/damianmarti/loogies) example.

I'm not very good at writing texts so feel free to discuss/change/share your ideas etc about README.md and the main page.tsx

Also, text on SpeedRunEthereum.com should be changed. Created PR https://github.com/BuidlGuidl/SpeedRunEthereum/pull/203 but currently in draft

And, we can also change images since it's other loogies, but we can do it later

Thanks @Pabl0cks for the idea and @damianmarti for your example and quick migration to SE-2!

I think we need to invite Austin to review texts and app but later when it is polished better

### CODE REVIEW

**Review by damianmarti — APPROVED** [review]
Everything looks and works great!!

**Review by Pabl0cks — APPROVED** [review]
GJ @rin-st!! It's looking good to me. And thanks @damianmarti for the great base 🙌

Pushed some minor changes to the Readme and tweaked RWD a bit. Feel free to change or undo anything you don't like pls!

Maybe for future iterations:

- Would be cool to have a section after the "Quest Journal", showcasing the most interesting technical points of the Challenge. Like we had in the [Multisig-break-down](https://github.com/scaffold-eth/se-2-challenges/tree/challenge-6-multisig?tab=readme-ov-file#-quick-break-down-)
- Should we add a couple of loogie images to the hero section of /loogies ? Too much text and we don't see a loogie until we mint some. But maybe not worth it since is just an example!

**Comment by rin-st** [comment]
Thanks Pablo! Good changes!

> Would be cool to have a section after the "Quest Journal", showcasing the most interesting technical points of the Challenge. Like we had in the [Multisig-break-down](https://github.com/scaffold-eth/se-2-challenges/tree/challenge-6-multisig?tab=readme-ov-file#-quick-break-down-)

https://github.com/scaffold-eth/se-2-challenges/issues/185

> Should we add a couple of loogie images to the hero section of /loogies ? Too much text and we don't see a loogie until we mint some. But maybe not worth it since is just an example!

I added one simple svg above the h1 in `/loogies` and `/your-loogies` (probably we need to change it to `my-loogies`) but left it as it was originally. Also made paddings smaller so I can see first row of nfts at least on my notebook

Снимок экрана 2024-06-12 в 13 29 41

Снимок экрана 2024-06-12 в 13 30 03

**Comment by Pabl0cks** [comment]
> I added one simple svg above the h1 in /loogies and /your-loogies (probably we need to change it to my-loogies) but left it as it was originally. Also made paddings smaller so I can see first row of nfts at least on my notebook

Looking better with the loogies you added :)

I've deleted the base test in https://github.com/scaffold-eth/se-2-challenges/pull/184/commits/29ddccba00c6d7b32d2f2480ca622ef80d7a1516. Not sure if deleting the test file is enough, or if there is some file that needs to be updated too.

**Comment by rin-st** [comment]
> I've deleted the base test in https://github.com/scaffold-eth/se-2-challenges/commit/29ddccba00c6d7b32d2f2480ca622ef80d7a1516. Not sure if deleting the test file is enough, or if there is some file that needs to be updated too.

Yes, it's enough, thanks!

**Comment by rin-st** [comment]
Thank you @Pabl0cks and @damianmarti, merging this!

**Pull request merged**
