### PR TITLE
fix inputs breaks UI & update EtherInput to take in .number values

### LINKED ISSUE #44: Challenge 4 - Invalid Inputs
- [ ] The ethToToken, Deposit, and Withdraw inputs will only allow a '.' if you first type in a 0.  We should allow them to type something like '.5' instead of forcing '0.5'.

- [ ] The tokenToEth input throws the following error when anything other than a number is entered, including a '.'
image

This should behave in the same way the other inputs do where if you type a non number or decimal it omits it.

### PR DESCRIPTION
**Pull request by technophile-04**
### Demo : 

https://github.com/scaffold-eth/se-2-challenges/assets/80153681/17b0fbb2-dd2e-41e6-837e-77a9f49e8ad1

Fixes #44 

<details>
<summary>My Contract solution if anyone wants refer : </summary>
      
            pragma solidity >=0.8.0 <0.9.0;
            // SPDX-License-Identifier: MIT
    
    import "@openzeppelin/contracts/token/ERC20/IERC20.sol";
    import "@openzeppelin/contracts/utils/math/SafeMath.sol";
    
    /**
     * @title DEX
     * @author stevepham.eth and m00npapi.eth
     * @notice this is a single token pair reserves DEX, ref: "Scaffold-ETH Challenge 4" as per https://speedrunethereum.com/, README.md and full branch (front-end) made with lots of inspiration from pre-existing example repos in scaffold-eth organization.
     */
    contract DEX {
        /* ========== GLOBAL VARIABLES ========== */
    
        uint256 public totalLiquidity; //total amount of liquidity provider tokens (LPTs) minted (NOTE: that LPT "price" is tied to the ratio, and thus price of the assets within this AMM)
        mapping(address => uint256) public liquidity; //liquidity of each depositor
        using SafeMath for uint256; //outlines use of SafeMath for uint256 variables
        IERC20 token; //instantiates the imported contract
    
        /* ========== EVENTS ========== */
    
        /**
         * @notice Emitted when ethToToken() swap transacted
         */
        event EthToTokenSwap(
            address swapper,
            string txDetails,
            uint256 ethInput,
            uint256 tokenOutput
        );
    
        /**
         * @notice Emitted when tokenToEth() swap transacted
         */
        event TokenToEthSwap(
            address swapper,
            string txDetails,
            uint256 tokensInput,
            uint256 ethOutput
        );
    
        /**
         * @notice Emitted when liquidity provided to DEX and mints LPTs.
         */
        event LiquidityProvided(
            address liquidityProvider,
            uint256 tokensInput,
            uint256 ethInput,
            uint256 liquidityMinted
        );
    
        /**
         * @notice Emitted when liquidity removed from DEX and decreases LPT count within DEX.
         */
        event LiquidityRemoved(
            address liquidityRemover,
            uint256 tokensOutput,
            uint256 ethOutput,
            uint256 liquidityWithdrawn
        );
    
        /* ========== CONSTRUCTOR ========== */
    
        constructor(address token_addr) public {
            token = IERC20(token_addr); //specifies the token address that will hook into the interface and be used through the variable 'token'
        }
    
        /* ========== MUTATIVE FUNCTIONS ========== */
    
        /**
         * @notice initializes amount of tokens that will be transferred to the DEX itself from the erc20 contract mintee (and only them based on how Balloons.sol is written). Loads contract up with both ETH and Balloons.
         * @param tokens amount to be transferred to DEX
         * @return totalLiquidity is the number of LPTs minting as a result of deposits made to DEX contract
         * NOTE: since ratio is 1:1, this is fine to initialize the totalLiquidity (wrt to balloons) as equal to eth balance of contract.
         */
        function init(uint256 tokens) public payable returns (uint256) {
            require(totalLiquidity == 0, "DEX: init - already has liquidity");
            totalLiquidity = address(this).balance;
            liquidity[msg.sender] = totalLiquidity;
            require(
                token.transferFrom(msg.sender, address(this), tokens),
                "DEX: init - transfer did not transact"
            );
            return totalLiquidity;
        }
    
        /**
         * @notice returns yOutput, or yDelta for xInput (or xDelta)
         */
        function price(
            uint256 xInput,
            uint256 xReserves,
            uint256 yReserves
        ) public view returns (uint256 yOutput) {
            uint256 xInputWithFee = xInput.mul(997);
            uint256 numerator = xInputWithFee.mul(yReserves);
            uint256 denominator = (xReserves.mul(1000)).add(xInputWithFee);
            return (numerator / denominator);
        }
    
        /**
         * @notice returns liquidity for a user. Note this is notneeded typically due to the `liquidity()` mapping variable being public and having a getter as a result. This is left though as it is used within the front end code (App.jsx).
         */
        function getLiquidity(address lp) public view returns (uint256) {
            return liquidity[lp];
        }
    
        /**
         * @notice sends Ether to DEX in exchange for $BAL
         */
        function ethToToken() public payable returns (uint256 tokenOutput) {
            require(msg.value > 0, "cannot swap 0 ETH");
            uint256 ethReserve = address(this).balance.sub(msg.value);
            uint256 token_reserve = token.balanceOf(address(this));
            uint256 tokenOutput = price(msg.value, ethReserve, token_reserve);
    
            require(
                token.transfer(msg.sender, tokenOutput),
                "ethToToken(): reverted swap."
            );
            emit EthToTokenSwap(
                msg.sender,
                "Eth to Balloons",
                msg.value,
                tokenOutput
            );
            return tokenOutput;
        }
    
        /**
         * @notice sends $BAL tokens to DEX in exchange for Ether
         */
        function tokenToEth(uint256 tokenInput) public returns (uint256 ethOutput) {
            require(tokenInput > 0, "cannot swap 0 tokens");
            uint256 token_reserve = token.balanceOf(address(this));
            uint256 ethOutput = price(
                tokenInput,
                token_reserve,
                address(this).balance
            );
            require(
                token.transferFrom(msg.sender, address(this), tokenInput),
                "tokenToEth(): reverted swap."
            );
            (bool sent, ) = msg.sender.call{value: ethOutput}("");
            require(sent, "tokenToEth: revert in transferring eth to you!");
            emit TokenToEthSwap(
                msg.sender,
                "Balloons to ETH",
                ethOutput,
                tokenInput
            );
            return ethOutput;
        }
    
        /**
         * @notice allows deposits of $BAL and $ETH to liquidity pool
         * NOTE: parameter is the msg.value sent with this function call. That amount is used to determine the amount of $BAL needed as well and taken from the depositor.
         * NOTE: user has to make sure to give DEX approval to spend their tokens on their behalf by calling approve function prior to this function call.
         * NOTE: Equal parts of both assets will be removed from the user's wallet with respect to the price outlined by the AMM.
         */
        function deposit() public payable returns (uint256 tokensDeposited) {
            require(msg.value > 0, "Must send value when depositing");
            uint256 ethReserve = address(this).balance.sub(msg.value);
            uint256 tokenReserve = token.balanceOf(address(this));
            uint256 tokenDeposit;
    
            tokenDeposit = (msg.value.mul(tokenReserve) / ethReserve).add(1);
            uint256 liquidityMinted = msg.value.mul(totalLiquidity) / ethReserve;
            liquidity[msg.sender] = liquidity[msg.sender].add(liquidityMinted);
            totalLiquidity = totalLiquidity.add(liquidityMinted);
    
            require(token.transferFrom(msg.sender, address(this), tokenDeposit));
            emit LiquidityProvided(
                msg.sender,
                liquidityMinted,
                msg.value,
                tokenDeposit
            );
            return tokenDeposit;
        }
    
        /**
         * @notice allows withdrawal of $BAL and $ETH from liquidity pool
         * NOTE: with this current code, the msg caller could end up getting very little back if the liquidity is super low in the pool. I guess they could see that with the UI.
         */
        function withdraw(
            uint256 amount
        ) public returns (uint256 eth_amount, uint256 token_amount) {
            require(
                liquidity[msg.sender] >= amount,
                "withdraw: sender does not have enough liquidity to withdraw."
            );
            uint256 ethReserve = address(this).balance;
            uint256 tokenReserve = token.balanceOf(address(this));
            uint256 ethWithdrawn;
    
            ethWithdrawn = amount.mul(ethReserve) / totalLiquidity;
    
            uint256 tokenAmount = amount.mul(tokenReserve) / totalLiquidity;
            liquidity[msg.sender] = liquidity[msg.sender].sub(amount);
            totalLiquidity = totalLiquidity.sub(amount);
            (bool sent, ) = payable(msg.sender).call{value: ethWithdrawn}("");
            require(sent, "withdraw(): revert in transferring eth to you!");
            require(token.transfer(msg.sender, tokenAmount));
            emit LiquidityRemoved(msg.sender, amount, ethWithdrawn, tokenAmount);
            return (ethWithdrawn, tokenAmount);
        }
    }
   

   
</details>

### CODE REVIEW

**Comment by rin-st** [comment]
hey @technophile-04 ! Gj! But I have some questions

- why to allow to click "Send" when we already show that input value is wrong (red border)? I think we need to disable buttons.
- is "." a wrong value? I think it should be equal to 0, and hence convertible. What do you think?

and it's not a [hydration error](https://nextjs.org/docs/messages/react-hydration-error)

**Comment by technophile-04** [comment]
Tysm Rinnat for review 🙌

> why to allow to click "Send" when we already show that input value is wrong (red border)? I think we need to disable buttons.

Umm not sure about I just wanted to show developers the error message lol so that they can learn, also one thing, I was also wondering weather instead of taking input in ether unit we should take it in `wei` unit (The input will have * which developer need to hit manualy to multiply by 10^18 ) again for developers learnings 

Ideally we should disable "Send" btn and take input in ether unit in production app, but just wanted to keep it raw similar to SE-1 challenge so that people can learn 

But I am fine with anything 🙌 cc @ZakGriffith and @Pabl0cks for their thoughts 

> is "." a wrong value? I think it should be equal to 0, and hence convertible. What do you think?

Umm in SE-2 `main` branch we are showing error for ".", I think it will be easy to solve just handling only "." case separately but if its get too messier I would probably leave

**Comment by Pabl0cks** [comment]
Good job @technophile-04 and nice suggestions @rin-st !!  🙌

> why to allow to click "Send" when we already show that input value is wrong (red border)? I think we need to disable buttons.

Reading you both, after changing my mind a couple of times 🤯, I see this could be an interesting approach, let me know what do you think:

- I think is good to let users input ether unit in frontend and `wei` in `Debug contracts`. That way we teach them good practices in how to build for the end user, but having in mind the base unit to work with in contracts is `wei`.
- Disabling send button is the best practice to show them in order to build production apps, but I think experiencing the transaction error it's also part of the learning experience.  
How about explaining in the README, maybe in a "_Side Quest_", to ask them what happend when they input a non numeric or negative number, and asking them to prevent it in the frontend by disabling "_Send button_", or even adding more evaluations in the contract level to give more accurate error messages on each case?

> is "." a wrong value? I think it should be equal to 0, and hence convertible. What do you think?

Maybe this is a bit edge case, I think we could assume that if an user writes a "." he is going to input a decimal number, and if he didn't write any number after "." is an error / he forgot to do it? If so I would probably just leave it like that.

**Comment by rin-st** [comment]
Thanks for quick answers!

> I was also wondering weather instead of taking input in ether unit we should take it in wei unit (The input will have * which developer need to hit manualy to multiply by 10^18 ) again for developers learnings

If we return it to `IntegerInput`, we need to add it to `EtherInput` too, for consistency. Because I think it's strange to input value in Eth to `EtherInput`, but in wei to `IntegerInput` below it, especially when values are equivalent at the start and you have a chart comparing that values.

> Ideally we should disable "Send" btn and take input in ether unit in production app, but just wanted to keep it raw similar to SE-1 challenge so that people can learn

But it was in Eth in SE-1, or am I wrong?

> Umm in SE-2 main branch we are showing error for ".", I think it will be easy to solve just handling only "." case separately but if its get too messier I would probably leave

Yep, let's leave it for now

---

@Pabl0cks good points, I agree!

**Comment by ZakGriffith** [comment]
> * I think is good to let users input ether unit in frontend and `wei` in `Debug contracts`. That way we teach them good practices in how to build for the end user, but having in mind the base unit to work with in contracts is `wei`.

I agree with this.  Best to keep the challenge front ends using ether.  Throughout the challenges, we do walk them through using the debug tab while converting to wei, and the front ends using ether.

I also agree with keeping the send buttons available, even when it is an obvious error.  Let them send it to get a feel for how these errors look.

> * is "." a wrong value? I think it should be equal to 0, and hence convertible. What do you think?

I don't have an opinion on this one, either way is okay.

This looks really good btw!  Very smooth.

**Comment by technophile-04** [comment]
> I think is good to let users input ether unit in frontend and wei in Debug contracts. 

> We return it to IntegerInput, we need to add it to EtherInput too, for consistency.

> I agree with this. Best to keep the challenge front ends using ether. Throughout the challenges, we do walk them through using the debug tab while converting to wei,


I agree with you all, really appreciate it !! Tysm all 🙌

---

- [X] User will entering the amount in ether uint on `dex` UI 
- [X] Keeping the "Send" btn enabled to show the error directly on UI 

I think both are handled already so merging this 🙌. Feel free to create more new issues around it, thanks again all !!

**Pull request merged**
