### PR TITLE
Challenge 5 backmerge v2

### PR DESCRIPTION
**Pull request by rin-st**

### CODE REVIEW

**Comment by Pabl0cks** [comment]
Nice job @rin-st !! 🙌

Been playing with the Challenge and found those issues, some of them are strange and make me believe I could have something wrong in my code, because first one didn't seem to happend in the last version, but now when I try it, it's happening also there 🤯
If it doesn't happend to you LMK and I'll try with another code.

- When I go to Streamer tab (either with Guru or with Rube) I get this error spammed:
  ```
  Error: VM Exception while processing transaction: reverted with reason string 'channel is not closing'
      at Streamer.fundChannel (contracts/Streamer.sol:26)
      at Streamer.timeLeft (contracts/Streamer.sol:36)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async HardhatNode.runCall 
  ```      
- As a Guru, when you delete text from the Wisdom you are providing to one of the Rubes, it discounts the amount of ETH received. I think (may be wrong) until now, it always fixed the max amount of characters you provided, even if then you deleted some text.
- As a Guru, when you delete characters from one Wisdom, and then click on another Wisdom text box, the first Wisdom received ETH changes to 0, and therefore, Cash out button turns inactive.
- When closed my second channel with the 2nd Rube, received this error:
  ```
   Error: VM Exception while processing transaction: reverted with panic code 0x11 (Arithmetic operation underflowed or overflowed outside of an unchecked block)
        at Streamer.timeLeft (contracts/Streamer.sol:38)
        at processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async HardhatNode.runCall (E:\GitHub\se-2-
  ```
- After receiving the error, it keep getting spammed (along with the first error ( 'channel is not closing'), and the screen wouldn't refresh when trying to change to Home/Debug/Block explorer sections, had to do a browser refresh to make the screen actually refresh with the new section content.

**Comment by Pabl0cks** [comment]
Thanks for the fast review and fix @rin-st, both errors are fixed now 🎉

You're right, the `timeLeft` function from the contract I took was completly broken 😥

> - As a Guru, when you delete text from the Wisdom you are providing to one of the Rubes, it discounts the amount of ETH received. I think (may be wrong) until now, it always fixed the max amount of characters you provided, even if then you deleted some text.
> - As a Guru, when you delete characters from one Wisdom, and then click on another Wisdom text box, the first Wisdom received ETH changes to 0, and therefore, Cash out button turns inactive.

I've been trying more the other 2 errors left, and I think they come from WAGMI migration, not from current backmerge. 
- At commit af00b8249b9b99269d0a3d2da6419a7278afd78f they were working as intended (pre WAGMI migration)
- At commit f1f0853eae9a69adc13c20256a6857e84bccbd8d it was doing strange stuff when you had 2 channels opened, I think with 1 channel it was working OK. Here is a [video](https://www.loom.com/share/fdd9882eee7c41d882d4354957759f73?sid=3460ebaf-b880-4214-90ba-ea54c21e99fe) I filmed.

**Comment by rin-st** [comment]
Thank you @Pabl0cks ! Tried it yesterday and it worked, but now it bugged again 🤷‍♂️  . Will recheck it

**Comment by rin-st** [comment]
fixed
https://github.com/scaffold-eth/se-2-challenges/assets/25638585/65da9513-4fe6-42bc-be8b-b9c49b372bc0

**Comment by Pabl0cks** [comment]
Just realized Checkpoint 5 got commented at some point, probably in WAGMI upgrade. 

I've pushed the code commented, if it was  a intented change, just LMK and I'll revert it and tweak the Readme a bit.

**Review by Pabl0cks — APPROVED** [review]
Incredible job @rin-st, is working really nice now.

Very hard challenge with such a weird and hard to debug errors and you nailed it 🙌🔥

**Pull request merged**
