### PR TITLE
Challenge 2 next14 migration

### PR DESCRIPTION
**Pull request by rin-st**
Migration of challenge 2 to next 14 and last se-2 changes

TODO:
- [x] fix tests

### CODE REVIEW

**Review by Pabl0cks — COMMENTED** [review]
Great job @rin-st !! Looking good to me, only added a couple of small tweaks on readme and default page titles.

I'm having a problem when I deploy to Vercel. Everything seems to be working nicely in the deployed website, but when I have the UI in light mode, and change to Debug tab, or I disconnect+connect wallet, UI reloads with dark mode.

**Comment by technophile-04** [comment]
Thanks @rin-st looks good ! 

> I'm having a problem when I deploy to Vercel. Everything seems to be working nicely in the deployed website, but when I have the UI in light mode, and change to Debug tab, or I disconnect+connect wallet, UI reloads with dark mode.

Yeah :( This is present in main SE-2 too just created https://github.com/scaffold-eth/scaffold-eth-2/issues/706 will probably handle it 🙌

**Comment by rin-st** [comment]
> Yeah :( This is present in main SE-2 too just created https://github.com/scaffold-eth/scaffold-eth-2/issues/706 will probably handle it 🙌

Thanks for letting me know!

**Comment by Pabl0cks** [comment]
> I'm having a problem when I deploy to Vercel. Everything seems to be working nicely in the deployed website, but when I have the UI in light mode, and change to Debug tab, or I disconnect+connect wallet, UI reloads with dark mode.

Fixed after importing the latest changes from SE-2. Thanks @technophile-04 and @rin-st!! GJ 🙌

**Review by Pabl0cks — APPROVED** [review]

**Pull request merged**
