### PR TITLE
Challenge 0 next14 migration

### PR DESCRIPTION
**Pull request by rin-st**
Migration of challenge 0 to next 14 and last se-2 changes

TODO:
- [x] fix tests

### CODE REVIEW

**Review by Pabl0cks — APPROVED** [review]
Good job @rin-st!! It looks great to me! 🙌

Manually added last fixes on `base-challenge-template` branch, since they were really small.
Did some changes on the Readme and tweaked default page title to match previous version.

**Comment by Pabl0cks** [comment]
Thinking about next14 integration in the Challenges, would it be a good idea to wait to have (at least) Chal0-1-2 ready to merge and merge them 3 at the same time?

I'm thinking at the newcomers doing challenge 0 with app router and then moving back to page router in the next challenges and getting confuse.

**Comment by carletex** [comment]
> Thinking about next14 integration into the Challenges, would it be a good idea to wait to have (at least) Chal0-1-2 ready to merge and merge them 3 at the same time?

I think this is a good idea. Since the migration for each challenge seems to be fast, it'll be ideal if we do the migration + test => merge the first 3 challenges at the same time.

**Comment by rin-st** [comment]
> Thinking about next14 integration into the Challenges, would it be a good idea to wait to have (at least) Chal0-1-2 ready to merge and merge them 3 at the same time?

Agree, good idea

> it'll be ideal if we do the migration + test

Btw tests are broken 😐, converting to draft for now

**Comment by rin-st** [comment]
> I've just realized that I got some errors when trying to deploy to Vercel, on /ipfsUpload and /ipfsDownload pages. error seems related to missing module './fetch.node'. Tried installing node-fetch but didn't seem to fix it.

Thanks! It seems something wrong with ipfs client, looks like it should work from node.js. Will check it tomorrow. Also, `kubo-rpc-client` lib is still [WIP](https://www.npmjs.com/package/kubo-rpc-client#work-in-progress). It refers to [ipfs-http-client](https://www.npmjs.com/package/ipfs-http-client), which is superseded by [Helia](https://github.com/ipfs/helia). Probably moving to Helia can help. Will check it.

Other than that, all migrations and tests for challenges 0, 1, 2 completed

**Comment by rin-st** [comment]
- Moved ipfs interactions to server side `/api/...`
- Added `ipfs-utils` package and added it to serverComponentsExternalPackages in next.config [link](https://github.com/web3-storage/w3up/issues/1183#issuecomment-1836526101)
```ts
experimental: {
    serverComponentsExternalPackages: ["ipfs-utils"],
  },
```
- Changed next/dynamic to [react.lazy](https://github.com/mac-s-g/react-json-view/issues/296#issuecomment-1762905309) for react-json-view since with dynamic it doesn't work properly and also cause build error (see issue from the link)

It seems everything working fine

**Comment by Pabl0cks** [comment]
Really good job tackling those build errors, everything is working great to me too, including tests. TYSM 🙌

**Comment by rin-st** [comment]
Updated challenges 0-2 after https://github.com/scaffold-eth/se-2-challenges/pull/132. It was fast :)
For me everything working well, nothing broke. I'm planning to merge these challenges in 1-2 days, so if you have time you can also make some tests before it.

**Comment by Pabl0cks** [comment]
> For me everything working well, nothing broke. I'm planning to merge these challenges in 1-2 days, so if you have time you can also make some tests before it.

Chal 0 working great to me also! TYSM @rin-st 🙌

**Comment by rin-st** [comment]
Thank you very much @Pabl0cks ! Merging challenges 0-2

**Pull request merged**
