### PR TITLE
chall 0: wagmi, viem, daisy migration

### PR DESCRIPTION
**Pull request by technophile-04**
### Description : 

Back merged `base-template-challenge` using `git merge base-template-challenge --squash`. 

Most of the conflicts were resolved automatically. There we some minor merge conflicts resolved them also regarding `yarn.lock` conflicts doing `yarn install`  automatically fixes conflicts in `yarn.lock` 🙌

Tested and works fine but would love if someone could also test once if something is not break🙌

### CODE REVIEW

**Review by Pabl0cks — CHANGES_REQUESTED** [review]
It's working great 🙌, just found a couple of things:

- Errors on first Access to "My NFTs" tab -> "Error fetching all collectibles".

  Happens only after a `yarn install` + `yarn chain` + `yarn deploy` + `yarn start` combo. It fires the #X amount of errors (equal to the number of NFTs minted in my previous deploy) so I feel it has something to do with local cache.

- Tiny nitpick on IPFS Upload/Download. 

  When clicking on "Upload to IPFS" or "Download from IPFS" buttons, it does a flickering effect, I suppose from a unintended reload from React.
  
  In `ipfsUpload.tsx` case, chatGPT suggests me to move `const DynamicReactJson = dynamic(import("react-json-view"), { ssr: false });` outside from `const IpfsUpload:`, it seems to do the job but I'm not sure if it would have some unexpected side-effects.
  
  Here is vid from flickering with this PR code vs oldcode Sepolia deploy with no flickering:
  https://www.loom.com/share/4d147bc6717644418329a9f686884168

**Comment by technophile-04** [comment]
> In ipfsUpload.tsx case, chatGPT suggests me to move const DynamicReactJson = dynamic(import("react-json-view"), { ssr: false }); outside from const IpfsUpload:, it seems to do the job but I'm not sure if it would have some unexpected side-effects.

Tysm  !!! Lol that was my rookie mistake, So the problem was since we had declared `const DynamicReactJson` inside of component, whenever you click "Upload to IPFS" , `loading` and  some other states updates and react re-runs the component again with updated states, now since we had declared `const DynamicReactJson` inside component it was also getting executed. Lol I wonder where my mind was while declaring it inside the component


> Happens only after a yarn install + yarn chain + yarn deploy + yarn start combo. It fires the #X amount of errors (equal to the number of NFTs minted in my previous deploy) so I feel it has something to do with local cache.

Yeah I think its `wagmi` cache issue, I have just pushed a minor tweak at [4f50a81](https://github.com/scaffold-eth/se-2-challenges/pull/74/commits/4f50a815fbe74af7605c3cf84818723c20b72e78) could you please check 🙌

**Review by Pabl0cks — APPROVED** [review]

**Comment by Pabl0cks** [comment]
> Yeah I think its wagmi cache issue, I have just pushed a minor tweak at [4f50a81](https://github.com/scaffold-eth/se-2-challenges/pull/74/commits/4f50a815fbe74af7605c3cf84818723c20b72e78) could you please check 🙌

Now is working great! GJ!! 🔥

**Comment by rin-st** [comment]
updated burner wallets info

**Review by rin-st — APPROVED** [review]

**Comment by technophile-04** [comment]
> Counter updated, but nft with previous index metadata isn't minted. It's very minor here, since it's written before that the user should grab ETH from the faucet.

Yeah, actually SE-1 challenge-0 had same thing...But yup I agree we should rely on index from `contract` just pushed a tweak [6d27e02](https://github.com/scaffold-eth/se-2-challenges/pull/74/commits/6d27e0205c8896506df0b6cac8f09fc6654ccb26) , lol it shows lots changes to contract due to code formatting but what I did was : 

```diff
- Counters.Counter private tokenIdCounter;
+ Counters.Counter public tokenIdCounter;
```

And used that variable to track the state on frontend 🙌

**Comment by rin-st** [comment]
works great! merging this

**Pull request merged**
