### PR TITLE
Challenge 4 dex

### PR DESCRIPTION
**Pull request by ZakGriffith**
**Changes**

- A handful of ReadMe wording updates and some additions/deletions. Feel free to discuss.
- Slight wording change in DEX.sol comments since we are not including a solutions file with this challenge.

**Other thoughts**
- It is unclear to me what this line is saying and what exactly to do.  Any ideas on how to clean this up?
_💡 Hints: See this [link](https://hackernoon.com/formulas-of-uniswap-a-deep-dive), solve for the change in the Output Reserve. See the section in that link up to the uniswap v3 title._

- Do we still need this line?  It is kind of a bummer that if they are seeing this, they likely did a copy/paste job in the challenge.
_It is okay if it says your contract is already verified. Copy the addresses of BAL.sol and DEX.sol and search them on sepolia Etherscan to find the correct URL you need to submit this challenge._

### CODE REVIEW

**Comment by Pabl0cks** [comment]
> - A handful of ReadMe wording updates and some additions/deletions. Feel free to discuss.
> - Slight wording change in DEX.sol comments since we are not including a solutions file with this challenge.

Nice improvements on the explanations @ZakGriffith, much clearer. I like the Goals/Checks additions too.

You also catched that Challenge closing section was not there, I totally missed it!. Good job !! 🙌

Added a nitpicky review, can just ignore if you feel is not necesary.

---

> It is unclear to me what this line is saying and what exactly to do. Any ideas on how to clean this up?
💡 Hints: See this [link](https://hackernoon.com/formulas-of-uniswap-a-deep-dive), solve for the change in the Output Reserve. See the section in that link up to the uniswap v3 title.

I don't understand that either. What I tend to think (but can be very wrong since I lack the context on this) is we can make use of that article to understand more about how the Output Reserve works. 

If my assumption is correct, we could change it to:

> 💡 Hints: See this [link](https://hackernoon.com/formulas-of-uniswap-a-deep-dive), to dive more on how Uniswap V2 Output Reserve is calculated. See the first section in that link up to the uniswap v3 title.

---

> Do we still need this line? It is kind of a bummer that if they are seeing this, they likely did a copy/paste job in the challenge.
It is okay if it says your contract is already verified. Copy the addresses of BAL.sol and DEX.sol and search them on sepolia Etherscan to find the correct URL you need to submit this challenge.

Didn't know about that feature, is Etherescan checking if there are other contracts 100% equal and displaying this message? **I would probably delete it, yep!**

**Comment by ZakGriffith** [comment]
> I don't understand that either. What I tend to think (but can be very wrong since I lack the context on this) is we can make use of that article to understand more about how the Output Reserve works.
> 
> If my assumption is correct, we could change it to:
> 
> > 💡 Hints: See this [link](https://hackernoon.com/formulas-of-uniswap-a-deep-dive), to dive more on how Uniswap V2 Output Reserve is calculated. See the first section in that link up to the uniswap v3 title.

Totally agree that we need to use the article.

Does this "See the first section in that link up to the Uniswap v3 title" mean read this article from the top (The V2 recap) until you get to the first V3 section?  Just want to be super clear about where to lead them.  We need to get the wording right because there is a hell of a lot going on in that article.

> Didn't know about that feature, is Etherescan checking if there are other contracts 100% equal and displaying this message? **I would probably delete it, yep!**

Yup, it sure does.  Happened 100% of the time in Challenge-0 where they do not have to edit the contract code to submit the challenge.  We do have this wording in challenge 0, so it should be safe to remove it here, will do.  Thank you!

**Comment by rin-st** [comment]
Looks good to me!

> 💡 Hints: See this [link](https://hackernoon.com/formulas-of-uniswap-a-deep-dive), to dive more on how Uniswap V2 Output Reserve is calculated. See the first section in that link up to the uniswap v3 title.

Agree. We can probably change to the exact section title but I'm not sure. Something like `See the first section in that link up to "Concentrated Liquidity of Uniswap V3 title"` or `See the first section "A Brief Revisit of Uniswap V2" in that link`

> Does this "See the first section in that link up to the Uniswap v3 title" mean read this article from the top (The V2 recap) until you get to the first V3 section?

I think, yes. We don't need other parts of the article for this challenge.

**Comment by Pabl0cks** [comment]
> Agree. We can probably change to the exact section title but I'm not sure. Something like See the first section in that link up to "Concentrated Liquidity of Uniswap V3 title" or See the first section "A Brief Revisit of Uniswap V2" in that link

I like the 2nd one! `See the first section "A Brief Revisit of Uniswap V2" in that link`. It's concise. 

We could also add at the end of it: `, you can skip Uniswap V3 explanations for this challenge`. But maybe it would be babysitting our speedrunners too much?

**Comment by rin-st** [comment]
> We could also add at the end of it: , you can skip Uniswap V3 explanations for this challenge. But maybe it would be babysitting our speedrunners too much?

Yes, I think it's redundant

**Pull request merged**
