### PR TITLE
Challenge 1 wagmi 2 backmerge

### PR DESCRIPTION
**Pull request by rin-st**

### CODE REVIEW

**Review by Pabl0cks — COMMENTED** [review]
Is looking good to me! The challenge is working fine, but found some edge case that we might want to check.

In `/staker-ui` if you change the `targetNetworks` from your connected network (hardhat for example), to another network (sepolia for example) you get this error instead of the "Wrong network" message from rainbow.

image

Doing the same at homepage, it works fine.

**Review by Pabl0cks — APPROVED** [review]
> Doing the same at homepage, it works fine.

TY! Working great now

**Comment by rin-st** [comment]
- [ ] TODO: fix notification after update. Looks like we need to rewrite se-2 `getParsedError` function. But probably I'm wrong

Снимок экрана 2024-05-01 в 19 55 03

**Comment by rin-st** [comment]
fixed by locking viem version

**Comment by rin-st** [comment]
Added last changes, updated `useBalance` to `useWatchBalance`, tested. Working fine.

**Comment by Pabl0cks** [comment]
Just did a final test and looking fine to me 🙌

**Pull request merged**
